# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  testes-unitarios:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Executa testes unitários!
        
  deploy-hml:
    runs-on: ubuntu-latest
    environment: 
      name: hml
      url: 'http://rupestrim.com.br/projeto_inicial_hml'
    needs: testes-unitarios
    steps:
      - name: Run a one-line script
        run: echo Deploy em Homologação!        
                
  testes:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Executa testes de sistema e infra!
        
  deploy-prod:
    runs-on: ubuntu-latest
    environment: 
      name: prod
      url: 'http://rupestrim.com.br/projeto_inicial_prod'
    needs: deploy-hml
    steps:
      - name: Run a one-line script
        run: echo Deploy em Produção!
        
  validacao:
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
      - name: Run a one-line script
        run: echo A atualização é avaliada e validada!
